
DROP TABLE P1 CASCADE CONSTRAINTS;

CREATE TABLE P1 (
	ID INTEGER,
	MOVE INTEGER,
	PLAYED INTEGER DEFAULT 0,
        PRIMARY KEY(ID)); 

--insert into P2 (ID,MOVE) values (); 


DROP TABLE RESULT_TABLE CASCADE CONSTRAINTS;

CREATE TABLE RESULT_TABLE (
	ID INTEGER,
	MOVE_P1 VARCHAR2(8),
	MOVE_P2 VARCHAR2(8),
	MATCH_RESULT VARCHAR2(8),
        PRIMARY KEY(ID)); 

	
--insert into RESULT_TABLE (ID,MOVE_P1,MOVE_P2,MATCH_RESULT) values (); 		